In [ ]:
1. צרי מערך באורך 10 של מספרים שלמים רנדומליים בין 1 ל-50 וחשבי את הממוצע של המספרים

In [3]:
pip install numpy


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [20]:
arr = np.random.randint(0, 50,size=(10))
arr

array([30, 18, 22, 41, 48,  1,  9, 31, 41, 14], dtype=int32)

In [21]:
np.mean(arr)

np.float64(25.5)

In [ ]:
2. צרי שני מערכים דו מימדיים בגודל 3, חברי אותם, ובדקי מה הממוצע של התוצאה

In [33]:
a1 = np.random.randint(0,5,size=(3,3))
a2 = np.random.randint(0,5,size=(3,3))   
a1
a2               

array([[3, 4, 4],
       [0, 2, 3],
       [3, 4, 3]], dtype=int32)

In [34]:
a1

array([[1, 2, 0],
       [1, 0, 4],
       [3, 0, 4]], dtype=int32)

In [35]:
a3 = a1 + a2
a3

array([[4, 6, 4],
       [1, 2, 7],
       [6, 4, 7]], dtype=int32)

In [36]:
np.mean(a3)

np.float64(4.555555555555555)

In [ ]:
3. צרי מערך של 20 מספרים שלמים רנדומליים בין 1 ל-100. מצאי את כל המספרים שגדולים מ-50 במערך זה.

In [38]:
arr2 = np.random.randint(0, 100,size=(20))
arr2

array([69, 38, 52, 63, 85, 99, 70, 62,  0, 82, 93, 64, 56, 35, 53, 89, 64,
       62, 86, 52], dtype=int32)

In [42]:
filter = x > 50
arr3 = arr2[filter]
arr3

NameError: name 'x' is not defined